#!/bin/bash

function can_lock() {
    # Check if the screen is locked or DPMS is Disabled
    if [[ $(xset -q | grep 'Monitor is On') ]] || [[ $(xset -q | grep 'DPMS is Disabled') ]]; then
	return 1 # can't lock
    else
	return 0 # can lock
    fi
}

while true; do
    if ! can_lock; then
        sleep 10
    else
        for ((i = 1; i <= 300; i++)); do
            if ! can_lock; then
                break
            fi
            sleep 1
        done
        if can_lock; then
            systemctl suspend
        fi
    fi
done
