#!/bin/bash

while true; do
    # Check if the screen is locked
    if [[ $(xset -q | grep 'Monitor is On') ]]; then
        # Screen is unlocked, reset timer
        sleep 10  # Check every 10 seconds
    else
        # Screen is locked, start the countdown
        for ((i = 1; i <= 300; i++)); do
            # Check if the screen is still locked
            if [[ $(xset -q | grep 'Monitor is On') ]]; then
                break
            fi
            sleep 1  # Wait for 1 second
        done
        # If the screen is still locked after 5 minutes, suspend
        if ! [[ $(xset -q | grep 'Monitor is On') ]]; then
            systemctl suspend
        fi
    fi
done
